In [143]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
% matplotlib inline

In [144]:
data = pd.read_excel('/Users/pein/Desktop/data(1).xlsx')

In [145]:
data.head()

,uid,provinceId,gender,gender_right,Age,createOn,createOn_Timerange,orderNum,LastConsuMe_TimeRange,totalFee,SingtotalFee,ActiveDays,ViewGoodsNum,ConsumeOrNot
0,1000,11,1,1,30,2012-06-10,1696,1,25,29.9,29.9,9,101.0,0
1,1001,33,1,1,31,2012-06-10,1696,1,17,49.0,49.0,9,39.0,1
2,1001745,44,0,1,28,2013-09-09,1240,2,28,79.8,49.9,5,17.0,0
3,1003120,14,1,1,23,2013-09-09,1240,1,15,95.0,95.0,9,52.0,1
4,1003236,32,0,1,29,2013-09-09,1240,4,23,202.9,68.0,5,25.0,0

In [146]:
data['Age_right'] = 0
correct = ((data.Age>10) & (data.Age<90))
data.Age_right[correct] = 1

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [147]:
data.head()

,uid,provinceId,gender,gender_right,Age,createOn,createOn_Timerange,orderNum,LastConsuMe_TimeRange,totalFee,SingtotalFee,ActiveDays,ViewGoodsNum,ConsumeOrNot,Age_right
0,1000,11,1,1,30,2012-06-10,1696,1,25,29.9,29.9,9,101.0,0,1
1,1001,33,1,1,31,2012-06-10,1696,1,17,49.0,49.0,9,39.0,1,1
2,1001745,44,0,1,28,2013-09-09,1240,2,28,79.8,49.9,5,17.0,0,1
3,1003120,14,1,1,23,2013-09-09,1240,1,15,95.0,95.0,9,52.0,1,1
4,1003236,32,0,1,29,2013-09-09,1240,4,23,202.9,68.0,5,25.0,0,1

In [148]:
# Use mask in the replace with the outliers
outlier = (data.Age<10)
data['Age'][outlier] = 25
outlier1 = (data.Age>90)
data['Age'][outlier1] = 25

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [149]:
data.describe()

,uid,provinceId,gender,gender_right,Age,createOn_Timerange,orderNum,LastConsuMe_TimeRange,totalFee,SingtotalFee,ActiveDays,ViewGoodsNum,ConsumeOrNot,Age_right
count,2.850000e+04,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000,27303.000000,28500.000000,28500.000000
mean,5.107024e+06,29.818491,0.138596,0.883368,29.188772,370.065228,1.520351,17.572421,222.252596,179.477617,4.190456,19.899535,0.339263,0.821193
std,2.241194e+06,14.673534,0.593854,0.320986,8.067643,422.730675,1.649305,7.628036,279.814575,193.206159,4.371444,30.574202,0.473468,0.383197
min,1.000000e+03,11.000000,-1.000000,0.000000,10.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,3.500968e+06,12.000000,0.000000,1.000000,25.000000,27.000000,1.000000,12.000000,78.900000,59.000000,1.000000,4.000000,0.000000,1.000000
50%,5.569924e+06,31.000000,0.000000,1.000000,27.000000,192.000000,1.000000,18.000000,173.000000,158.000000,2.000000,10.000000,0.000000,1.000000
75%,7.199240e+06,42.000000,1.000000,1.000000,33.000000,581.000000,1.000000,24.000000,269.000000,219.000000,5.000000,24.000000,1.000000,1.000000
max,7.567869e+06,65.000000,1.000000,1.000000,82.000000,1931.000000,79.000000,29.000000,10661.900000,7740.000000,31.000000,1340.000000,1.000000,1.000000

In [150]:
data.drop('createOn',1)

,uid,provinceId,gender,gender_right,Age,createOn_Timerange,orderNum,LastConsuMe_TimeRange,totalFee,SingtotalFee,ActiveDays,ViewGoodsNum,ConsumeOrNot,Age_right
0,1000,11,1,1,30,1696,1,25,29.9,29.9,9,101.0,0,1
1,1001,33,1,1,31,1696,1,17,49.0,49.0,9,39.0,1,1
2,1001745,44,0,1,28,1240,2,28,79.8,49.9,5,17.0,0,1
3,1003120,14,1,1,23,1240,1,15,95.0,95.0,9,52.0,1,1
4,1003236,32,0,1,29,1240,4,23,202.9,68.0,5,25.0,0,1
5,1003794,33,0,1,21,1239,1,19,198.0,198.0,4,3.0,0,1
6,100423,51,1,1,46,1603,2,16,25.8,15.9,20,9.0,1,1
7,1004261,42,1,1,34,1239,1,6,208.0,208.0,1,12.0,0,1
8,1004359,23,0,1,25,1239,1,15,259.0,259.0,3,7.0,1,1
9,100438,22,1,1,27,1603,1,6,39.0,39.0,2,3.0,0,1
10,100466,37,0,1,31,1603,2,23,33.8,17.9,2,4.0,1,1
11,1004675,33,0,1,24,1239,1,24,183.0,183.0,3,20.0,0,1
12,1004965,31,0,1,26,1239,2,9,456.0,298.0,2,8.0,0,1
13,1005374,42,0,1,28,1239,1,13,16.9,16.9,1,4.0,1,1
14,1006224,11,0,1,45,1238,10,10,654.4,172.0,18,66.0,1,1
15,1006313,50,0,1,24,1238,1,15,196.0,196.0,3,3.0,0,1
16,1006412,33,0,1,37,1238,1,8,148.0,148.0,1,3.0,0,1
17,1007042,14,0,1,24,1238,1,12,49.0,49.0,9,66.0,1,1
18,1007424,50,0,1,25,1238,5,12,734.9,348.0,14,50.0,0,1
19,1008332,43,1,1,41,1238,1,29,139.0,139.0,4,3.0,0,1
20,1008614,22,1,1,16,1238,1,7,168.0,168.0,2,2.0,0,1
21,1009284,42,1,1,24,1237,1,18,148.0,148.0,1,4.0,0,1
22,1009745,11,0,1,33,1237,1,18,347.0,347.0,4,13.0,1,1
23,1009805,51,1,1,31,1237,1,18,129.0,129.0,2,1.0,0,1
24,1009894,44,0,1,27,1237,1,29,1448.0,1448.0,5,16.0,0,1
25,1009897,35,0,1,27,1237,1,28,170.0,170.0,3,4.0,0,1
26,1010601,42,0,1,34,1237,1,27,138.0,138.0,10,3.0,0,1
27,1010791,44,0,1,36,1237,1,27,70.0,70.0,2,8.0,0,1
28,1010795,31,0,1,24,1237,1,11,109.0,109.0,8,48.0,1,1
29,1010906,11,0,1,23,1237,1,25,36.9,36.9,10,5.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28470,987887,11,0,1,35,1245,2,22,276.0,138.0,2,15.0,0,1
28471,988958,37,1,1,27,1245,1,17,16.9,16.9,3,2.0,0,1
28472,989600,31,1,1,47,1245,1,18,30.0,30.0,1,2.0,1,1
28473,989670,45,1,1,28,1245,1,29,26.8,26.8,5,4.0,0,1
28474,990570,33,0,1,30,1244,1,17,161.0,161.0,1,1.0,0,1
28475,990724,13,0,1,28,1244,1,13,284.0,284.0,3,2.0,0,1
28476,99079,51,0,1,29,1604,2,18,59.8,29.9,20,5.0,0,1
28477,99097,51,0,1,38,1604,2,3,68.7,39.9,1,19.0,0,1
28478,991269,31,1,1,32,1244,1,0,215.0,215.0,1,6.0,1,1
28479,99258,52,0,1,26,1604,1,10,158.0,158.0,4,7.0,0,1
28480,993034,44,1,1,34,1243,1,26,428.0,428.0,3,2.0,0,1
28481,993086,11,0,1,35,1243,1,11,148.0,148.0,1,11.0,0,1
28482,993479,53,0,1,40,1243,1,22,9.9,9.9,2,10.0,0,1
28483,993934,44,1,1,32,1243,1,28,186.0,186.0,1,2.0,0,1
28484,993940,50,0,1,33,1243,1,13,168.0,168.0,7,38.0,0,1
28485,994001,44,0,1,45,1243,5,17,227.6,78.0,17,37.0,1,1
28486,994047,37,0,1,23,1243,1,7,70.0,70.0,6,32.0,1,1
28487,994594,44,0,1,29,1243,4,16,352.0,189.0,8,51.0,0,1
28488,994951,61,0,1,20,1243,1,24,26.9,26.9,9,95.0,1,1
28489,995251,22,0,1,24,1242,4,10,797.8,640.0,20,153.0,1,1
28490,995376,34,1,1,26,1242,1,28,148.0,148.0,5,15.0,1,1
28491,995436,11,1,1,48,1242,1,23,14.9,14.9,9,2.0,1,1
28492,996792,53,0,1,44,1242,1,22,116.0,116.0,1,1.0,1,1
28493,997225,11,0,1,23,1242,1,17,148.0,148.0,1,NaN,1,1
28494,997244,14,1,1,28,1242,1,22,39.0,39.0,5,3.0,0,1
28495,998166,53,0,1,23,1241,1,13,266.0,266.0,7,57.0,1,1
28496,998179,32,1,1,36,1241,2,27,88.0,68.0,3,1.0,0,1
28497,998314,11,1,1,38,1241,1,15,209.0,209.0,3,4.0,1,1
28498,998367,50,0,1,26,1241,1,24,13.9,13.9,10,64.0,1,1
28499,999443,35,1,1,21,1241,3,0,192.0,85.0,14,18.0,1,1

In [151]:
data = data[['uid', 'provinceId', 'gender', 'gender_right', 'Age', 'createOn_Timerange',
            'orderNum', 'LastConsuMe_TimeRange','totalFee', 'SingtotalFee',
            'ActiveDays','ViewGoodsNum','Age_right','ConsumeOrNot']]

In [152]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28500 entries, 0 to 28499
Data columns (total 14 columns):
uid                      28500 non-null int64
provinceId               28500 non-null int64
gender                   28500 non-null int64
gender_right             28500 non-null int64
Age                      28500 non-null int64
createOn_Timerange       28500 non-null int64
orderNum                 28500 non-null int64
LastConsuMe_TimeRange    28500 non-null int64
totalFee                 28500 non-null float64
SingtotalFee             28500 non-null float64
ActiveDays               28500 non-null int64
ViewGoodsNum             27303 non-null float64
Age_right                28500 non-null int64
ConsumeOrNot             28500 non-null int64
dtypes: float64(3), int64(11)
memory usage: 3.0 MB

In [153]:
data.drop('uid',1)

,provinceId,gender,gender_right,Age,createOn_Timerange,orderNum,LastConsuMe_TimeRange,totalFee,SingtotalFee,ActiveDays,ViewGoodsNum,Age_right,ConsumeOrNot
0,11,1,1,30,1696,1,25,29.9,29.9,9,101.0,1,0
1,33,1,1,31,1696,1,17,49.0,49.0,9,39.0,1,1
2,44,0,1,28,1240,2,28,79.8,49.9,5,17.0,1,0
3,14,1,1,23,1240,1,15,95.0,95.0,9,52.0,1,1
4,32,0,1,29,1240,4,23,202.9,68.0,5,25.0,1,0
5,33,0,1,21,1239,1,19,198.0,198.0,4,3.0,1,0
6,51,1,1,46,1603,2,16,25.8,15.9,20,9.0,1,1
7,42,1,1,34,1239,1,6,208.0,208.0,1,12.0,1,0
8,23,0,1,25,1239,1,15,259.0,259.0,3,7.0,1,1
9,22,1,1,27,1603,1,6,39.0,39.0,2,3.0,1,0
10,37,0,1,31,1603,2,23,33.8,17.9,2,4.0,1,1
11,33,0,1,24,1239,1,24,183.0,183.0,3,20.0,1,0
12,31,0,1,26,1239,2,9,456.0,298.0,2,8.0,1,0
13,42,0,1,28,1239,1,13,16.9,16.9,1,4.0,1,1
14,11,0,1,45,1238,10,10,654.4,172.0,18,66.0,1,1
15,50,0,1,24,1238,1,15,196.0,196.0,3,3.0,1,0
16,33,0,1,37,1238,1,8,148.0,148.0,1,3.0,1,0
17,14,0,1,24,1238,1,12,49.0,49.0,9,66.0,1,1
18,50,0,1,25,1238,5,12,734.9,348.0,14,50.0,1,0
19,43,1,1,41,1238,1,29,139.0,139.0,4,3.0,1,0
20,22,1,1,16,1238,1,7,168.0,168.0,2,2.0,1,0
21,42,1,1,24,1237,1,18,148.0,148.0,1,4.0,1,0
22,11,0,1,33,1237,1,18,347.0,347.0,4,13.0,1,1
23,51,1,1,31,1237,1,18,129.0,129.0,2,1.0,1,0
24,44,0,1,27,1237,1,29,1448.0,1448.0,5,16.0,1,0
25,35,0,1,27,1237,1,28,170.0,170.0,3,4.0,1,0
26,42,0,1,34,1237,1,27,138.0,138.0,10,3.0,1,0
27,44,0,1,36,1237,1,27,70.0,70.0,2,8.0,1,0
28,31,0,1,24,1237,1,11,109.0,109.0,8,48.0,1,1
29,11,0,1,23,1237,1,25,36.9,36.9,10,5.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28470,11,0,1,35,1245,2,22,276.0,138.0,2,15.0,1,0
28471,37,1,1,27,1245,1,17,16.9,16.9,3,2.0,1,0
28472,31,1,1,47,1245,1,18,30.0,30.0,1,2.0,1,1
28473,45,1,1,28,1245,1,29,26.8,26.8,5,4.0,1,0
28474,33,0,1,30,1244,1,17,161.0,161.0,1,1.0,1,0
28475,13,0,1,28,1244,1,13,284.0,284.0,3,2.0,1,0
28476,51,0,1,29,1604,2,18,59.8,29.9,20,5.0,1,0
28477,51,0,1,38,1604,2,3,68.7,39.9,1,19.0,1,0
28478,31,1,1,32,1244,1,0,215.0,215.0,1,6.0,1,1
28479,52,0,1,26,1604,1,10,158.0,158.0,4,7.0,1,0
28480,44,1,1,34,1243,1,26,428.0,428.0,3,2.0,1,0
28481,11,0,1,35,1243,1,11,148.0,148.0,1,11.0,1,0
28482,53,0,1,40,1243,1,22,9.9,9.9,2,10.0,1,0
28483,44,1,1,32,1243,1,28,186.0,186.0,1,2.0,1,0
28484,50,0,1,33,1243,1,13,168.0,168.0,7,38.0,1,0
28485,44,0,1,45,1243,5,17,227.6,78.0,17,37.0,1,1
28486,37,0,1,23,1243,1,7,70.0,70.0,6,32.0,1,1
28487,44,0,1,29,1243,4,16,352.0,189.0,8,51.0,1,0
28488,61,0,1,20,1243,1,24,26.9,26.9,9,95.0,1,1
28489,22,0,1,24,1242,4,10,797.8,640.0,20,153.0,1,1
28490,34,1,1,26,1242,1,28,148.0,148.0,5,15.0,1,1
28491,11,1,1,48,1242,1,23,14.9,14.9,9,2.0,1,1
28492,53,0,1,44,1242,1,22,116.0,116.0,1,1.0,1,1
28493,11,0,1,23,1242,1,17,148.0,148.0,1,NaN,1,1
28494,14,1,1,28,1242,1,22,39.0,39.0,5,3.0,1,0
28495,53,0,1,23,1241,1,13,266.0,266.0,7,57.0,1,1
28496,32,1,1,36,1241,2,27,88.0,68.0,3,1.0,1,0
28497,11,1,1,38,1241,1,15,209.0,209.0,3,4.0,1,1
28498,50,0,1,26,1241,1,24,13.9,13.9,10,64.0,1,1
28499,35,1,1,21,1241,3,0,192.0,85.0,14,18.0,1,1

In [154]:
data_train = data.iloc[:,1:-1]
data_test = data.iloc[:,-1]

In [155]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28500 entries, 0 to 28499
Data columns (total 12 columns):
provinceId               28500 non-null int64
gender                   28500 non-null int64
gender_right             28500 non-null int64
Age                      28500 non-null int64
createOn_Timerange       28500 non-null int64
orderNum                 28500 non-null int64
LastConsuMe_TimeRange    28500 non-null int64
totalFee                 28500 non-null float64
SingtotalFee             28500 non-null float64
ActiveDays               28500 non-null int64
ViewGoodsNum             27303 non-null float64
Age_right                28500 non-null int64
dtypes: float64(3), int64(9)
memory usage: 2.6 MB

In [156]:
data_train['provinceId'] = data_train['provinceId'].astype('category')

In [157]:
data_train['ViewGoodsNum'] = data_train['ViewGoodsNum'].fillna(1)
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28500 entries, 0 to 28499
Data columns (total 12 columns):
provinceId               28500 non-null category
gender                   28500 non-null int64
gender_right             28500 non-null int64
Age                      28500 non-null int64
createOn_Timerange       28500 non-null int64
orderNum                 28500 non-null int64
LastConsuMe_TimeRange    28500 non-null int64
totalFee                 28500 non-null float64
SingtotalFee             28500 non-null float64
ActiveDays               28500 non-null int64
ViewGoodsNum             28500 non-null float64
Age_right                28500 non-null int64
dtypes: category(1), float64(3), int64(8)
memory usage: 2.4 MB

In [178]:
data_train.iloc[:,1:] = data_train.iloc[:,1:].apply(lambda x: (x-np.mean(x))/np.std(x))
data_train.head()

,provinceId,gender,gender_right,Age,createOn_Timerange,orderNum,LastConsuMe_TimeRange,totalFee,SingtotalFee,ActiveDays,ViewGoodsNum,Age_right
0,11,1.450555,0.36336,0.100555,3.13665,-0.315503,0.973738,-0.687441,-0.774200,1.100238,2.714976,0.466627
1,33,1.450555,0.36336,0.224509,3.13665,-0.315503,-0.075043,-0.619180,-0.675340,1.100238,0.659538,0.466627
2,44,-0.233389,0.36336,-0.147353,2.05793,0.290824,1.367031,-0.509105,-0.670682,0.185192,-0.069810,0.466627
3,14,1.450555,0.36336,-0.767124,2.05793,-0.315503,-0.337238,-0.454783,-0.437248,1.100238,1.090517,0.466627
4,32,-0.233389,0.36336,-0.023399,2.05793,1.503477,0.711543,-0.069163,-0.576998,0.185192,0.195407,0.466627

In [179]:
# the LR model for the consumerLoss
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

print(data_train.head())
clf = LogisticRegression()
clf.fit(data_train, data_test)

result = clf.score(data_train,data_test)
result

  provinceId    gender  gender_right       Age  createOn_Timerange  orderNum  \
0         11  1.450555       0.36336  0.100555             3.13665 -0.315503
1         33  1.450555       0.36336  0.224509             3.13665 -0.315503
2         44 -0.233389       0.36336 -0.147353             2.05793  0.290824
3         14  1.450555       0.36336 -0.767124             2.05793 -0.315503
4         32 -0.233389       0.36336 -0.023399             2.05793  1.503477

   LastConsuMe_TimeRange  totalFee  SingtotalFee  ActiveDays  ViewGoodsNum  \
0               0.973738 -0.687441     -0.774200    1.100238      2.714976
1              -0.075043 -0.619180     -0.675340    1.100238      0.659538
2               1.367031 -0.509105     -0.670682    0.185192     -0.069810
3              -0.337238 -0.454783     -0.437248    1.100238      1.090517
4               0.711543 -0.069163     -0.576998    0.185192      0.195407

   Age_right
0   0.466627
1   0.466627
2   0.466627
3   0.466627
4   0.466627

0.73684210526315785

In [180]:
data_train_train = data_train.iloc[:15000,:]
data_train_test = data_train.iloc[15000:,:]
data_test_train = data_test.iloc[:15000]
data_test_test = data_test.iloc[15000:]

In [181]:
clf1 = LogisticRegression()
clf1.fit(data_train_train, data_test_train)

predict = clf1.predict(data_train_test)
accuracy_score(data_test_test,predict)

0.79222222222222227

In [182]:
# the SVM model for consumerLoss
from sklearn import svm
clf2 = svm.SVC()
clf2.fit(data_train_train, data_test_train)
result1 = clf2.score(data_train_train, data_test_train)
result1

0.70866666666666667

In [184]:
predict2 = clf2.predict(data_train_test)
accuracy_score(data_test_test,predict2)

0.79577777777777781