In [18]:
import  tushare as ts

In [19]:
ts.set_token('72ab08413e05484c457efe2136fe51a0e81f8f382bc31896636f182211755b26')

In [33]:
st = ts.Subject()

In [34]:
result=st.SocialDataXQ()
result

,ticker,statisticsDate,postNum,postPercent,insertTime,updateTime
0,1,2017-06-17 00:00:00,4.0,1.393728,2017-06-17 07:01:18,2017-06-17 07:03:02
1,1,2017-06-16 00:00:00,56.0,0.328619,2017-06-17 07:01:13,2017-06-17 07:02:59
2,1,2017-06-15 00:00:00,49.0,0.234787,2017-06-15 07:01:19,2017-06-16 07:03:04
3,1,2017-06-14 00:00:00,61.0,0.286856,2017-06-14 07:01:23,2017-06-15 07:03:02
4,1,2017-06-13 00:00:00,61.0,0.308533,2017-06-13 07:01:17,2017-06-14 07:03:23
5,1,2017-06-12 00:00:00,59.0,0.282108,2017-06-13 07:01:12,2017-06-13 07:03:05
6,1,2017-06-11 00:00:00,53.0,0.856635,2017-06-11 07:01:05,2017-06-12 07:02:52
7,1,2017-06-10 00:00:00,15.0,0.286533,2017-06-11 07:01:05,2017-06-11 07:02:45
8,1,2017-06-09 00:00:00,51.0,0.241775,2017-06-09 07:01:24,2017-06-10 07:03:18
9,1,2017-06-08 00:00:00,38.0,0.172226,2017-06-08 07:01:19,2017-06-09 07:03:28
10,1,2017-06-07 00:00:00,47.0,0.242380,2017-06-07 07:01:23,2017-06-08 07:03:11
11,1,2017-06-06 00:00:00,52.0,0.261938,2017-06-07 07:01:12,2017-06-07 07:03:20
12,1,2017-06-05 00:00:00,41.0,0.237131,2017-06-06 07:01:15,2017-06-06 07:03:10
13,1,2017-06-04 00:00:00,10.0,0.170911,2017-06-04 07:01:11,2017-06-05 07:03:04
14,1,2017-06-03 00:00:00,43.0,0.903931,2017-06-03 07:01:16,2017-06-04 07:02:55
15,1,2017-06-02 00:00:00,47.0,0.271833,2017-06-03 07:01:09,2017-06-03 07:03:01
16,1,2017-06-01 00:00:00,52.0,0.275045,2017-06-01 07:01:18,2017-06-02 07:02:58
17,1,2017-05-31 00:00:00,42.0,0.252071,2017-05-31 07:01:13,2017-06-01 07:03:08
18,1,2017-05-30 00:00:00,21.0,0.434603,2017-05-30 07:01:02,2017-05-31 07:02:43
19,1,2017-05-29 00:00:00,20.0,0.673627,2017-05-29 07:01:07,2017-05-30 07:02:27
20,1,2017-05-28 00:00:00,9.0,0.235294,2017-05-29 07:01:07,2017-05-29 07:02:36
21,1,2017-05-27 00:00:00,23.0,0.400906,2017-05-27 07:01:16,2017-05-28 07:02:42
22,1,2017-05-26 00:00:00,42.0,0.226917,2017-05-26 07:01:15,2017-05-27 07:03:02
23,1,2017-05-25 00:00:00,75.0,0.425339,2017-05-26 07:01:08,2017-05-26 07:02:56
24,1,2017-05-24 00:00:00,41.0,0.229911,2017-05-24 07:01:18,2017-05-25 07:02:58
25,1,2017-05-23 00:00:00,47.0,0.239186,2017-05-24 07:01:06,2017-05-24 07:02:56
26,1,2017-05-22 00:00:00,39.0,0.229385,2017-05-23 07:01:08,2017-05-23 07:03:03
27,1,2017-05-21 00:00:00,7.0,0.118584,2017-05-22 07:01:05,2017-05-22 07:02:36
28,1,2017-05-20 00:00:00,15.0,0.313152,2017-05-21 07:01:05,2017-05-21 07:02:43
29,1,2017-05-19 00:00:00,36.0,0.202452,2017-05-20 07:01:10,2017-05-20 07:03:03
...,...,...,...,...,...,...
99970,2646,2017-04-19 00:00:00,NaN,0.000000,2017-04-20 10:01:12,2017-04-20 10:01:12
99971,2646,2017-04-18 00:00:00,1.0,0.005576,2017-04-19 07:02:26,2017-04-19 10:01:15
99972,2646,2017-04-17 00:00:00,NaN,0.000000,2017-04-18 10:01:25,2017-04-18 13:30:31
99973,2646,2017-04-16 00:00:00,NaN,0.000000,2017-04-17 10:01:09,2017-04-18 13:30:29
99974,2646,2017-04-15 00:00:00,NaN,0.000000,2017-04-16 10:01:13,2017-04-18 13:30:27
99975,2646,2017-04-14 00:00:00,1.0,0.005762,2017-04-15 07:02:24,2017-04-18 13:30:26
99976,2646,2017-04-13 00:00:00,NaN,0.000000,2017-04-14 10:01:11,2017-04-18 13:30:24
99977,2646,2017-04-12 00:00:00,2.0,0.011303,2017-04-13 07:02:15,2017-04-18 13:30:22
99978,2646,2017-04-11 00:00:00,NaN,0.000000,2017-04-12 10:01:11,2017-04-18 13:30:21
99979,2646,2017-04-10 00:00:00,3.0,0.015730,2017-04-11 07:02:16,2017-04-18 13:30:19
99980,2646,2017-04-09 00:00:00,NaN,0.000000,2017-04-10 10:01:14,2017-04-18 13:30:17
99981,2646,2017-04-08 00:00:00,NaN,0.000000,2017-04-09 10:01:15,2017-04-18 13:30:16
99982,2646,2017-04-07 00:00:00,NaN,0.000000,2017-04-08 10:01:13,2017-04-18 13:30:14
99983,2646,2017-04-06 00:00:00,NaN,0.000000,2017-04-07 10:01:14,2017-04-18 13:30:12
99984,2646,2017-04-05 00:00:00,NaN,0.000000,2017-04-06 10:01:11,2017-04-18 13:30:11
99985,2646,2017-04-04 00:00:00,NaN,0.000000,2017-04-05 10:01:13,2017-04-18 13:30:09
99986,2646,2017-04-03 00:00:00,NaN,0.000000,2017-04-04 10:01:17,2017-04-18 13:30:07
99987,2646,2017-04-02 00:00:00,NaN,0.000000,2017-04-03 10:01:09,2017-04-18 13:30:05
99988,2646,2017-04-01 00:00:00,NaN,0.000000,2017-04-02 10:01:09,2017-04-18 13:30:04
99989,2646,2017-03-31 00:00:00,NaN,0.000000,2017-04-01 10:01:10,2017-04-18 13:30:02
99990,2646,2017-03-30 00:00:00,NaN,0.000000,2017-03-31 10:01:14,2017-04-18 13:30:00
99991,2646,2017-03-29 00:00:00,1.0,0.005221,2017-03-30 07:02:16,2017-04-18 13:29:59
99992,2646,2017-03-28 00:00:00,1.0,0.005561,2017-03-29 07:02:24,2017-04-18 13:29:57
99993,2646,2017-03-27 00:00:00,NaN,0.000000,2017-03-28 10:01:14,2017-04-18 13:29:55
99994,2646,2017-03-26 00:00:00,NaN,0.000000,2017-03-27 10:01:08,2017-04-18 13:29:54
99995,2646,2017-03-25 00:00:00,NaN,0.000000,2017-03-26 10:01:10,2017-04-18 13:29:52
99996,2646,2017-03-24 00:00:00,NaN,0.000000,2017-03-25 10:01:09,2017-04-18 13:29:51
99997,2646,2017-03-23 00:00:00,2.0,0.009695,2017-03-24 07:02:19,2017-04-18 13:29:49
99998,2646,2017-03-22 00:00:00,3.0,0.014040,2017-03-23 07:02:15,2017-04-18 13:29:47
99999,2646,2017-03-21 00:00:00,1.0,0.004988,2017-03-22 07:02:15,2017-04-18 13:29:46

In [28]:
import matplotlib.pyplot as plt
%matplotlib inline
result.plot(x='statisticsDate',y='postNum')

KeyError: 'statisticsDate'

In [ ]:
import requests
import json
a = requests.get('url')
a.json()[1]